/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package middle;

import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author IBN 03
 */
public class graph extends javax.swing.JFrame {

    /**
     * Creates new form graph
     */
    public graph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jButton1.setText("Detection Ratio Comparison");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 140, 500, 70);

        jButton3.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jButton3.setText("ENERGY CONSUMPTION COMPARISON");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(120, 250, 500, 70);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("   Performance Comparison");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 70, 340, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1607253.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 490);

        setSize(new java.awt.Dimension(713, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultCategoryDataset Dataset = new DefaultCategoryDataset();
        Dataset.setValue(0.04, "Proposed", "400");
        Dataset.setValue(0.59, "Proposed", "600");
        Dataset.setValue(0.94, "Proposed", "800");
        Dataset.setValue(0.98, "Proposed", "1000");
        Dataset.setValue(0.01, "RM", "400");
        Dataset.setValue(0.06, "RM", "600");
        Dataset.setValue(0.29, "RM", "800");
        Dataset.setValue(0.29, "RM", "1000");
        Dataset.setValue(0.03, "LSM", "400");
        Dataset.setValue(0.55, "LSM", "600");
        Dataset.setValue(0.92, "LSM", "800");
        Dataset.setValue(0.95, "LSM", "1000");
        Dataset.setValue(0.01, "RED", "400");
        Dataset.setValue(0.10, "RED", "600");
        Dataset.setValue(0.45, "RED", "800");
        Dataset.setValue(0.58, "RED", "1000");
       
        JFreeChart chart = ChartFactory.createBarChart3D("Detection Ratio Of Replicas", "Total Number of Nodes", "Detection Ratio", Dataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot P = chart.getCategoryPlot();
        P.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame(" Detection ratio Comparison", chart);
        frame.setVisible(true);

        frame.setSize(450, 500);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultCategoryDataset Dataset = new DefaultCategoryDataset();
        Dataset.setValue(110, "Proposed", "400");
        Dataset.setValue(55, "Proposed", "600");
        Dataset.setValue(20, "Proposed", "800");
        Dataset.setValue(20, "Proposed", "1000");
        Dataset.setValue(60, "RM", "400");
        Dataset.setValue(70, "RM", "600");
        Dataset.setValue(85, "RM", "800");
        Dataset.setValue(85, "RM", "1000");
        Dataset.setValue(60, "LSM", "400");
        Dataset.setValue(50, "LSM", "600");
        Dataset.setValue(30, "LSM", "800");
        Dataset.setValue(30, "LSM", "1000");
        Dataset.setValue(55, "RED", "400");
        Dataset.setValue(55, "RED", "600");
        Dataset.setValue(55, "RED", "800");
        Dataset.setValue(55, "RED", "1000");
        JFreeChart chart = ChartFactory.createBarChart3D("Average Energy Consumed", "Total Number Of Nodes", "Average Consumed Energy", Dataset, PlotOrientation.VERTICAL, true, true, false);
        CategoryPlot P = chart.getCategoryPlot();
        P.setRangeGridlinePaint(Color.BLUE);
        ChartFrame frame = new ChartFrame("Average Energy Consumption", chart);
        frame.setVisible(true);

        frame.setSize(450, 500);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new graph().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
