/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package middle;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author IBN 03
 */
public class replicas extends javax.swing.JFrame {

    /**
     * Creates new form replicas
     */
    public replicas() {
        initComponents();
        a1.setVisible(false);
        a2.setVisible(false);
        a3.setVisible(false);
        a4.setVisible(false);
        a5.setVisible(false);
        a6.setVisible(false);
        a7.setVisible(false);
        a8.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b5.setVisible(false);
        b6.setVisible(false);
        b7.setVisible(false);
        b8.setVisible(false);
        c1.setVisible(false);
        c2.setVisible(false);
        c3.setVisible(false);
        c4.setVisible(false);
        c5.setVisible(false);
        c6.setVisible(false);
        c7.setVisible(false);
        c8.setVisible(false);
        d1.setVisible(false);
        d2.setVisible(false);
        d3.setVisible(false);
        d4.setVisible(false);
        d5.setVisible(false);
        d6.setVisible(false);
        d7.setVisible(false);
        d8.setVisible(false);
        e1.setVisible(false);
        e2.setVisible(false);
        e3.setVisible(false);
        e4.setVisible(false);
        e5.setVisible(false);
        e6.setVisible(false);
        e7.setVisible(false);
        e8.setVisible(false);
        z1.setVisible(false);
        z2.setVisible(false);
        z3.setVisible(false);
        z4.setVisible(false);
        z5.setVisible(false);
        z6.setVisible(false);
        
        rep1.setVisible(false);
        rep2.setVisible(false);
        rep3.setVisible(false);
        Thread tt = new Thread(new connect());
        tt.start();
    }
    class connect implements Runnable {

        public void run() {
            try {
               
                Thread.sleep(500);
                z1.setVisible(true);
                Thread.sleep(500);
                a1.setVisible(true);
                a2.setVisible(true);
                a3.setVisible(true);
                a4.setVisible(true);
                a5.setVisible(true);
                a6.setVisible(true);
                a7.setVisible(true);
                a8.setVisible(true);
                Thread.sleep(500);
                z2.setVisible(true);
                Thread.sleep(500);
                b1.setVisible(true);
                b2.setVisible(true);
                b3.setVisible(true);
                b4.setVisible(true);
                b5.setVisible(true);
                b6.setVisible(true);
                b7.setVisible(true);
                b8.setVisible(true);
                Thread.sleep(500);
                z3.setVisible(true);
                Thread.sleep(500);
                c1.setVisible(true);
                c2.setVisible(true);
                c3.setVisible(true);
                c4.setVisible(true);
                c5.setVisible(true);
                c6.setVisible(true);
                c7.setVisible(true);
                c8.setVisible(true);
                Thread.sleep(500);
                z4.setVisible(true);
                Thread.sleep(500);
                d1.setVisible(true);
                d2.setVisible(true);
                d3.setVisible(true);
                d4.setVisible(true);
                d5.setVisible(true);
                d6.setVisible(true);
                d7.setVisible(true);
                d8.setVisible(true);
                Thread.sleep(500);
                z5.setVisible(true);
                Thread.sleep(500);
                e1.setVisible(true);
                e2.setVisible(true);
                e3.setVisible(true);
                e4.setVisible(true);
                e5.setVisible(true);
                e6.setVisible(true);
                e7.setVisible(true);
                e8.setVisible(true);
                Thread.sleep(500);
               z6.setVisible(true);
                Thread.sleep(500);
                rep1.setVisible(true);
                rep2.setVisible(true);
                rep3.setVisible(true);
                JOptionPane.showMessageDialog(null, "Replicas Node","",2);
          

            } catch (InterruptedException ex) {
                Logger.getLogger(dataS.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        e4 = new javax.swing.JLabel();
        e8 = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        e5 = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        e7 = new javax.swing.JLabel();
        e6 = new javax.swing.JLabel();
        z6 = new javax.swing.JLabel();
        z5 = new javax.swing.JLabel();
        rep1 = new javax.swing.JLabel();
        rep2 = new javax.swing.JLabel();
        rep3 = new javax.swing.JLabel();
        z4 = new javax.swing.JLabel();
        z1 = new javax.swing.JLabel();
        z2 = new javax.swing.JLabel();
        z3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anim_ant.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 670, 110, 83);

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(b6);
        b6.setBounds(380, 460, 16, 20);

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(b4);
        b4.setBounds(400, 440, 16, 20);

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(b8);
        b8.setBounds(360, 440, 16, 20);

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(b2);
        b2.setBounds(380, 420, 16, 20);

        a5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(a5);
        a5.setBounds(250, 600, 16, 25);

        a3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(a3);
        a3.setBounds(270, 580, 16, 25);

        a7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(a7);
        a7.setBounds(230, 580, 16, 25);

        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(a1);
        a1.setBounds(250, 560, 16, 25);

        c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(c5);
        c5.setBounds(190, 400, 20, 20);

        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(c4);
        c4.setBounds(210, 390, 20, 20);

        c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(c8);
        c8.setBounds(170, 380, 20, 20);

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(c1);
        c1.setBounds(190, 370, 20, 20);

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(b5);
        b5.setBounds(380, 450, 16, 16);

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(b3);
        b3.setBounds(400, 430, 16, 16);

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(b7);
        b7.setBounds(360, 430, 16, 16);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(b1);
        b1.setBounds(380, 410, 16, 16);

        d1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(d1);
        d1.setBounds(350, 230, 20, 20);

        d4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(d4);
        d4.setBounds(370, 260, 20, 20);

        d8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(d8);
        d8.setBounds(330, 260, 20, 20);

        d2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(d2);
        d2.setBounds(350, 240, 20, 20);

        d6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(d6);
        d6.setBounds(350, 280, 20, 16);

        d3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(d3);
        d3.setBounds(370, 250, 20, 16);

        d7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(d7);
        d7.setBounds(330, 250, 20, 16);

        d5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(d5);
        d5.setBounds(350, 270, 20, 20);

        a6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(a6);
        a6.setBounds(250, 610, 16, 25);

        a4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(a4);
        a4.setBounds(270, 590, 16, 25);

        a8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(a8);
        a8.setBounds(230, 590, 16, 25);

        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(a2);
        a2.setBounds(250, 570, 16, 25);

        c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(c6);
        c6.setBounds(190, 410, 20, 20);

        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(c3);
        c3.setBounds(210, 380, 20, 20);

        c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(c7);
        c7.setBounds(170, 390, 20, 20);

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(c2);
        c2.setBounds(190, 360, 20, 20);

        e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(e1);
        e1.setBounds(180, 110, 20, 20);

        e4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(e4);
        e4.setBounds(200, 140, 20, 20);

        e8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(e8);
        e8.setBounds(160, 140, 20, 20);

        e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(e2);
        e2.setBounds(180, 120, 20, 20);

        e5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(e5);
        e5.setBounds(180, 160, 20, 16);

        e3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(e3);
        e3.setBounds(200, 130, 20, 16);

        e7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(e7);
        e7.setBounds(160, 130, 20, 16);

        e6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circle_orange (1).png"))); // NOI18N
        getContentPane().add(e6);
        e6.setBounds(180, 150, 20, 20);

        z6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rightwards_arrow_u2192_icon_48x48.png"))); // NOI18N
        getContentPane().add(z6);
        z6.setBounds(290, 100, 40, 30);

        z5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/north_west_arrow_u2196_icon_48x48.png"))); // NOI18N
        getContentPane().add(z5);
        z5.setBounds(250, 180, 50, 30);

        rep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Black-Circle.gif"))); // NOI18N
        getContentPane().add(rep1);
        rep1.setBounds(380, 90, 20, 30);

        rep2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Black-Circle.gif"))); // NOI18N
        getContentPane().add(rep2);
        rep2.setBounds(400, 100, 20, 30);

        rep3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Black-Circle.gif"))); // NOI18N
        getContentPane().add(rep3);
        rep3.setBounds(400, 80, 20, 30);

        z4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/north_east_.png"))); // NOI18N
        getContentPane().add(z4);
        z4.setBounds(260, 310, 40, 30);

        z1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/north_west_arrow_u2196_icon_48x48.png"))); // NOI18N
        getContentPane().add(z1);
        z1.setBounds(350, 630, 50, 30);

        z2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/north_east_.png"))); // NOI18N
        getContentPane().add(z2);
        z2.setBounds(310, 510, 40, 30);

        z3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/north_west_arrow_u2196_icon_48x48.png"))); // NOI18N
        getContentPane().add(z3);
        z3.setBounds(270, 400, 50, 30);

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Bloom Filter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 10, 350, 50);

        jButton1.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 80, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1607253.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 750, 760);

        setSize(new java.awt.Dimension(761, 798));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new abs().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(replicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(replicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(replicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(replicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new replicas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JLabel e5;
    private javax.swing.JLabel e6;
    private javax.swing.JLabel e7;
    private javax.swing.JLabel e8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel rep1;
    private javax.swing.JLabel rep2;
    private javax.swing.JLabel rep3;
    private javax.swing.JLabel z1;
    private javax.swing.JLabel z2;
    private javax.swing.JLabel z3;
    private javax.swing.JLabel z4;
    private javax.swing.JLabel z5;
    private javax.swing.JLabel z6;
    // End of variables declaration//GEN-END:variables
}
