/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exis;

import java.awt.FileDialog;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.net.Inet4Address;
import java.net.ServerSocket;
import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import middle.abs;

/**
 *
 * @author m
 */
public class Desti extends javax.swing.JFrame {

    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    public static String exe;
    String s1;
    StringBuffer buffer;
    String ipA, ipB, ipC, ipD;
    public int checkFlag = 0;
    String original;
    public String source;

    /**
     * Creates new form Client_side
     */
    public Desti() {

        initComponents();


        init();
        Date date = new Date();
        System.out.println(dateFormat.format(date));
        jTextField1.setText(dateFormat.format(date));
        jButton1.setEnabled(false);
        //  jTextArea2.setVisible(false);
        //  jScrollPane2.setVisible(false);


        Thread t = new Thread(new connect());
        t.start();
        try {
            jLabel6.setText(Inet4Address.getLocalHost().getHostAddress());
        } catch (Exception e) {
        }
    }

    private void init() {

        setTitle(source);
    }

    public class Conn implements Runnable {

        public void run() {
            for (int i = 100; i >= 25; i--) {
                try {
                    Thread.sleep(100);
                    jProgressBar1.setValue(i);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Desti.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    class connect implements Runnable {

        public void run() {
            try {


                ServerSocket ss = new ServerSocket(8401);
                Socket s = ss.accept();
                System.out.println("Receive");
                InputStream is = s.getInputStream();
                ObjectInputStream ois = new ObjectInputStream(is);
                ArrayList<String> array = (ArrayList<String>) ois.readObject();
                s1 = array.get(0);
                String s2 = array.get(0);
                int d = s2.length();
                String aa[] = s2.split("\n");
                for (int i = 1; i <= aa.length; i++) {
                    jTextArea2.append(" Packet  [" + i + "] : Received");
                    jTextArea2.append("\n");
                    Thread.sleep(100);

                }
                jTextArea2.append("\n File Received to Destination...!");
                Thread t = new Thread(new Conn());
                t.start();
                Thread.sleep(500);
                jTextArea1.setText(s2);
                jTextArea1.append("\n File Received to Destination...!");
                jButton1.setEnabled(true);
                is.close();
                ois.close();
                s.close();
                ss.close();
            } catch (Exception e) {
                System.out.println("OOPS! Errors are found -> " + e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recieved Data");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Recieved Data :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 210, 140, 30);

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Received Packet Details :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 220, 260, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 260, 410, 220);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(470, 260, 360, 210);

        jButton1.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jButton1.setText("Save ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 510, 110, 30);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(610, 90, 250, 30);

        jLabel3.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Energy_Level :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 90, 150, 30);

        jLabel4.setFont(new java.awt.Font("Cooper Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("File Recieving Time :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 90, 170, 30);

        jTextField1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 90, 220, 30);

        jLabel5.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Destination IP Address :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 240, 17);

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel6.setText(".");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 140, 190, 20);

        jButton2.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 33, 130, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1607253.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 890, 560);

        setSize(new java.awt.Dimension(906, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String ss = jTextArea1.getText();
            if (ss.length() > 0) {
                FileDialog fd = new FileDialog(this, "Save File As", FileDialog.SAVE);
                fd.setFile("temp.txt");
                fd.setDirectory("C:\\Documents and Settings\\JP1\\Desktop");
                fd.setVisible(true);
                String path = fd.getDirectory() + fd.getFile();
                FileOutputStream fos = new FileOutputStream(path);
                System.out.println(ss);
                byte[] b = ss.getBytes();
                fos.write(b);
                fos.close();
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        new abs().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desti().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
