/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exis;

import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author IBN 03
 */
public class NewJFrame extends javax.swing.JFrame {

    ObjectOutputStream oos, oos1, oos2;
    OutputStream os, os1, os2;
    ArrayList<String> array = new ArrayList<String>();
    String data, ipaddr;

    /**
     * Creates new form Router
     */
    public NewJFrame(String get, String ipA) {
        data = get;
        ipaddr = ipA;
        initComponents();
        jLabel1.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel24.setVisible(false);
        jLabel4.setVisible(false);
        jLabel23.setVisible(false);
        jLabel22.setVisible(false);
        jLabel25.setVisible(false);
        jLabel3.setVisible(false);
        jLabel2.setVisible(false);


        Thread t = new Thread(new connect());
        t.start();

    }

    class connect implements Runnable {

        public void run() {
            try {

                Thread.sleep(500);
                jLabel1.setVisible(true);

               // Thread.sleep(500);
             //   jLabel19.setVisible(true);
                Thread.sleep(1000);
                jLabel20.setVisible(true);
                Thread.sleep(1000);
                jLabel21.setVisible(true);
                Thread.sleep(1000);
                jLabel24.setVisible(true);
                Thread.sleep(1000);
                jLabel23.setVisible(true);
                Thread.sleep(1000);
                jLabel22.setVisible(true);
                Thread.sleep(1000);
                jLabel25.setVisible(true);
                Thread.sleep(500);
                jLabel3.setVisible(true);

                Thread.sleep(1000);
                jLabel4.setVisible(true);
                Thread.sleep(1000);
                jLabel2.setVisible(true);
                try {

                    array.add(0, data.toString());
                    Socket s2 = null;
                    String ip = ipaddr;
                    s2 = new Socket(ip, 8401);
                    os2 = s2.getOutputStream();
                    oos2 = new ObjectOutputStream(os2);
                    oos2.writeObject(array);
                    oos2.close();
                    os2.close();
                    s2.close();
                } catch (UnknownHostException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (InterruptedException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/source.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(673, 218, 30, 10);

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("File Received");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(740, 137, 110, 20);

        jLabel11.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("File Sender");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 130, 130, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/user.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 169, 110, 140);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/source.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(120, 219, 30, 10);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/source.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(194, 218, 30, 10);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/source.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(264, 218, 30, 10);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/source.png"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(511, 218, 30, 10);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/source.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(430, 218, 30, 10);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/source.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(349, 218, 30, 10);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/source.png"))); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(594, 218, 30, 10);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exis/user1.png"))); // NOI18N
        jLabel4.setText(" ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(740, 179, 135, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1607253.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 870, 480);

        setSize(new java.awt.Dimension(891, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame("", "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
